apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-api
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "name" . }}-api
    component: {{ .Values.api.service.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ports:
  - port: 80
    # targetPort: server-port
    targetPort: !!int {{ .Values.api.service.port }}
    name: http
    protocol: TCP
  selector:
    app: {{ template "name" . }}-api
    # component: {{ .Values.api.service.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  type: NodePort
