apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ .Release.Name }}-{{ .Values.global_config.name }}
data:
 {{- range $key, $value := .Values.global_config.data }}
  {{ $key }}: {{ $value | quote }}
 {{- end }}
  GET_HOSTS_FROM: dns
  POSTGRES_HOST: {{ .Release.Name }}-gcloud-sqlproxy
  REDIS_HOST: {{ .Release.Name }}-redis
