---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}-ingress
  labels:
    app: {{ template "name" . }}-ingress
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  {{- $apiHostBackend := required "Need a host backend for api defined in 'ingress' values" .Values.api.ingress.host_backend | quote }}

{{- if not .Values.STUPID_NO_TLS }}
  tls:
  - hosts:
    - {{ $apiHostBackend }}
    # already 'required' above
    secretName: {{ .Values.api.ingress.host_backend }}-tls
{{- end }}
  rules:
    - host: {{ $apiHostBackend }}
      http:
        paths:
      {{- $releaseName := .Release.Name }}
      {{- $fullName := include "fullname" . }}
      {{ range .Values.api.ingress.paths }}
        - path: {{ . }}
          backend:
            serviceName: {{ $fullName }}-api
            # This should be 80 - it is forwarded TO the service on port 80,
            # which then forwards it to the deployment on the port specified in
            # the input file
            servicePort: 80
      {{ end }}
