# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-04 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('django_demo', '0002_add_m2m_fields'), ('django_demo', '0003_auto_20180504_1406')]

    dependencies = [
        ('django_demo', '0001_initial'),
        ('organizations', '0002_model_update'),
        ('zconnect', '0002_create_other_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitegroup',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zconnect.Location'),
        ),
        migrations.AddField(
            model_name='demodevice',
            name='orgs',
            field=models.ManyToManyField(blank=True, help_text="Organizations that 'own' this device", related_name='device_set', related_query_name='device', to='organizations.Organization', verbose_name='organizations'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='mapping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mappings', to='django_demo.WiringMapping'),
        ),
        migrations.AddField(
            model_name='distributorgroup',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zconnect.Location'),
        ),
        migrations.AddField(
            model_name='companygroup',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='django_demo.DistributorGroup'),
        ),
        migrations.AddField(
            model_name='companygroup',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zconnect.Location'),
        ),
        migrations.AddField(
            model_name='companygroup',
            name='wiring_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_demo.WiringMapping'),
        ),
        migrations.AddField(
            model_name='distributorgroup',
            name='wiring_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_demo.WiringMapping'),
        ),
        migrations.AddField(
            model_name='demodevice',
            name='wiring_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_demo.WiringMapping'),
        ),
        migrations.AddField(
            model_name='sitegroup',
            name='wiring_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_demo.WiringMapping'),
        ),
    ]
