# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-04 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_demo', '0002_add_foreign_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='demodevice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zconnect.Product'),
        ),
        migrations.CreateModel(
            name='DemoProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='zconnect.Product')),
                ('wiring_mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_demo.WiringMapping')),
            ],
            options={
                'abstract': False,
            },
            bases=('zconnect.product',),
        ),
    ]
