# Generated by Django 2.0.5 on 2018-05-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_demo', '0003_add_demo_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demodevice',
            name='orgs',
            field=models.ManyToManyField(blank=True, help_text="Organizations that 'own' this device", related_name='devices', related_query_name='device', to='organizations.Organization', verbose_name='organizations'),
        ),
    ]
